### ISSUE TITLE
"Unexpected error" after login

### ISSUE THREAD

**Issue by rwillmer** [atoy40/meteor-accounts-cas#2]
I've got this partially working for me, but it's falling over at the final stage of the login process.

I have a login button on the meteor site. 

When I press it, the popup comes up with the CAS login at the CAS server.

When I login, the CAS server logs confirm that the login was successful.

But then the meteor popup changes to a URL similar to "http://localhost:3000/_cas/Y6syhx3saqcoAsxp5?ticket=ST-1393497698-X0NiTItRHfay9XepSAwqhS1U0hL8E5qU" and the popup text says only "Unexpected error".

The meteor server shows this:

```
W20140227-10:41:38.463(0)? (STDERR) 
W20140227-10:41:38.464(0)? (STDERR) events.js:72
W20140227-10:41:38.464(0)? (STDERR)         throw er; // Unhandled 'error' event
W20140227-10:41:38.465(0)? (STDERR)               ^
W20140227-10:41:38.465(0)? (STDERR) Error: getaddrinfo ENOTFOUND
W20140227-10:41:38.465(0)? (STDERR)     at errnoException (dns.js:37:11)
W20140227-10:41:38.473(0)? (STDERR)     at Object.onanswer [as oncomplete] (dns.js:124:16)
=> Exited with code: 8
```

Any ideas about what the problem is, or how I can debug it?

**Comment by corecache** [comment]
@atoy40 I stumbled upon this one today, the mentioned fix above never made it into the code, right?
